### ISSUE TITLE
Make TypeScript Definitions More Strict

### ISSUE THREAD

**Issue by nickytonline** [developit/linkstate#21]
Although the current TypeScript types for this package are valid, they cause issues with TypeScript projects that have strict mode enabled for the compiler options. The `e` parameter of the return type signature should not be an implicit `any`. It should be of type `Event` or a generic event type.

![image](https://user-images.githubusercontent.com/833231/57963704-3e0f7880-78f6-11e9-8714-ddc942c4798d.png)

**Comment by thisconnect** [comment]
Just ran into that issue too

![Screen Shot 2020-08-14 at 1 32 53 PM](https://user-images.githubusercontent.com/546900/90245379-d9add280-de32-11ea-84a8-8f3121e494f7.png)

**Comment by nickytonline** [comment]
Saw this in my feed for PRs on GH, so just following up as it affects folks that have strict mode enabled in TS.
